-- MySQL Script generated by MySQL Workbench
-- Fri Aug 18 13:41:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hrassist
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hrassist` ;

-- -----------------------------------------------------
-- Schema hrassist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hrassist` DEFAULT CHARACTER SET utf8 ;
USE `hrassist` ;

-- -----------------------------------------------------
-- Table `hrassist`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrassist`.`jobs` ;

CREATE TABLE IF NOT EXISTS `hrassist`.`jobs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `benefits` VARCHAR(45) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hrassist`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrassist`.`skills` ;

CREATE TABLE IF NOT EXISTS `hrassist`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hrassist`.`job_requirment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrassist`.`job_requirment` ;

CREATE TABLE IF NOT EXISTS `hrassist`.`job_requirment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `job_id` INT(11) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `skills_id` INT NOT NULL,
  PRIMARY KEY (`id`, `skills_id`),
  INDEX `job_id_idx` (`job_id` ASC),
  INDEX `fk_job_requirment_skills1_idx` (`skills_id` ASC),
  CONSTRAINT `FK_job_requirment-job`
    FOREIGN KEY (`job_id`)
    REFERENCES `hrassist`.`jobs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_job_requirment_skills1`
    FOREIGN KEY (`skills_id`)
    REFERENCES `hrassist`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hrassist`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrassist`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `hrassist`.`user_roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hrassist`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrassist`.`users` ;

CREATE TABLE IF NOT EXISTS `hrassist`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_role_id` INT(11) NOT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_users-user_roles_idx` (`user_role_id` ASC),
  CONSTRAINT `FK_users-user_roles`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `hrassist`.`user_roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `hrassist`.`personal_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrassist`.`personal_info` ;

CREATE TABLE IF NOT EXISTS `hrassist`.`personal_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personal_info_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_personal_info_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `hrassist`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrassist`.`user_education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrassist`.`user_education` ;

CREATE TABLE IF NOT EXISTS `hrassist`.`user_education` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `personal_info_id` INT(11) NOT NULL,
  `scool_name` VARCHAR(45) NULL DEFAULT NULL,
  `graduated_year` INT(11) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_user_education-personal-info_idx` (`personal_info_id` ASC),
  CONSTRAINT `FK_user_education-personal-info`
    FOREIGN KEY (`personal_info_id`)
    REFERENCES `hrassist`.`personal_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrassist`.`user_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrassist`.`user_skills` ;

CREATE TABLE IF NOT EXISTS `hrassist`.`user_skills` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `personal_info_id` INT(11) NOT NULL,
  `skills_id` INT NOT NULL,
  PRIMARY KEY (`id`, `skills_id`),
  INDEX `FK_user_skills-personal-info_idx` (`personal_info_id` ASC),
  INDEX `fk_user_skills_skills1_idx` (`skills_id` ASC),
  CONSTRAINT `FK_user_skills-personal-info`
    FOREIGN KEY (`personal_info_id`)
    REFERENCES `hrassist`.`personal_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_skills_skills1`
    FOREIGN KEY (`skills_id`)
    REFERENCES `hrassist`.`skills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hrassist`.`user_work_experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hrassist`.`user_work_experience` ;

CREATE TABLE IF NOT EXISTS `hrassist`.`user_work_experience` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `personal_info_id` INT(11) NOT NULL,
  `company_name` VARCHAR(45) NULL DEFAULT NULL,
  `position` VARCHAR(45) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_user_work_experience-personal-info_idx` (`personal_info_id` ASC),
  CONSTRAINT `FK_user_work_experience-personal-info`
    FOREIGN KEY (`personal_info_id`)
    REFERENCES `hrassist`.`personal_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
